### ISSUE TITLE
RND core sink

### ISSUE THREAD

**Issue by sparcmoonlight** [ChrisAdderley/NearFuturePropulsion#118]
Hi i try a compact probe based an RND 0,6, but allways sink.

Final try: Hammer booster, decoupler, probe core RND, 2 shrinked parachute on the side of core . fire it to the ocean, 2m/s touchdown and probe sink.
Same with vanilla hex core => don't sink.

Is this a valid feautre for the core or a bug?
How can the core stay saove on surface?

**Comment by ChrisAdderley** [comment]
This mod doesn't include probe cores.
