### ISSUE TITLE
Vasimir Plasma Thruster does not work with TweakScale

### ISSUE THREAD

**Issue by pyalot** [ChrisAdderley/NearFuturePropulsion#13]
When tweakscaling the vasimir plasma thruster (the smallest one) it consumes the same amount of fuel and makes the same amount of thrust.

![2015-12-25_00007](https://cloud.githubusercontent.com/assets/592826/12002944/707361a6-ab0e-11e5-9d65-e0cbeeca1174.jpg)

Other engines in NFP don't do that, for instance the Ion Thruster scales correctly:

![2015-12-25_00008](https://cloud.githubusercontent.com/assets/592826/12002954/9e53b08a-ab0e-11e5-8cfe-bb3375f5d532.jpg)

The stock ion engine also scales correctly.

**Comment by ChrisAdderley** [comment]
Expected behaviour - I don't support tweakscale.

**Comment by pyalot** [comment]
Ah, I see, it's a tweakscale patch, I'll file a ticket with them.

**Comment by pyalot** [comment]
Filed: https://github.com/Biotronic/TweakScale/issues/36
