### ISSUE TITLE
VABOrganizer Patch references undefined lithium subcategory

### ISSUE THREAD

**Issue by coldrifting** [ChrisAdderley/NearFuturePropulsion#139]
The VABOrganizer patch refers to a lithium subcategory, but It isn't created by VABOrganizer or NearFuturePropulsion, or even by FarFutureTechnolgies. The lithium defined in FarFutureTech is called lithiumFuel, so even if it is installed, lithium tanks from this mod will still show up in the misc subcategory.

**Comment by ChrisAdderley** [comment]
Update your version of VABOrganizer: https://github.com/post-kerbin-mining-corporation/VABOrganizer/blob/1e892eb01ba7123f698e78609cb12ca37a86f558/GameData/VABOrganizer/Subcategories/fuel.cfg#L45

**Comment by coldrifting** [comment]
Thanks, my bad
