### ISSUE TITLE
Problem with Near Future Propulsion in KSP 1.2

### ISSUE THREAD

**Issue by bastabox** [ChrisAdderley/NearFuturePropulsion#34]
I install Near Future Propulsion for my KSP in version 1.2
When i launch the game i have message : Unsupported version... Please use 1.2 
When i try to use Nuclear Reactor, he doesn't create energy.
Log : 
[ERR 17:43:13.888] Module FissionReactor threw during OnFixedUpdate: System.InvalidProgramException: Invalid IL code in NearFutureElectrical.FissionReactor:RecalculateRatios (single): IL_005a: stfld     0x0a0000d5

  at NearFutureElectrical.FissionReactor.DoFuelConsumption () [0x00000] in <filename unknown>:0 
  at NearFutureElectrical.FissionReactor.OnFixedUpdate () [0x00000] in <filename unknown>:0 
  at Part.ModulesOnFixedUpdate () [0x00000] in <filename unknown>:0 

I use latest version on Github.

**Comment by CobaltWolf** [comment]
Are you fucking retarded?

**Comment by bastabox** [comment]
Why ?
I install near future propulsion from github and I have reinstalled my game

**Comment by ChrisAdderley** [comment]
There is no release for 1.2 yet. If you just pull the repo you will not get what you want and it is not recommended unless you can compile and debug yourself.

**Comment by bastabox** [comment]
Why you send that ?



On Thu, Oct 20, 2016 at 10:03 PM +0200, "Matthew Mlodzienski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you fucking retarded?

-
