### ISSUE TITLE
Unique models for HeFT LH2 RCS thrusters

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/NearFuturePropulsion#42]
The LH2-converted MPDT RCS thrusters should get unique models, or at least textures.

**Comment by Bornholio** [comment]
How about just a Texture Change to a Black Banded Nozzle

say change https://github.com/ChrisAdderley/NearFuturePropulsion/blob/master/GameData/NearFuturePropulsion/Parts/RCS/rcsblock-electric/rcsblock-electric-01.dds
My ugly Gimp edit
https://www.dropbox.com/s/9kwp6c8ksugjjrf/rcsblock-electric-01H.dds?dl=0
