### ISSUE TITLE
vasimr engine(s) give errors & don't work in editor/VAB

### ISSUE THREAD

**Issue by LouisCyfer** [ChrisAdderley/NearFuturePropulsion#47]
plz check these engines!

- rightclick in VAB/editor --> breaks right click ability for all parts somehow, have to reenter the VAB to use rightclick again
- also give NRE's in spaceflight while switching from argon (sry i just played with the options ingame and stumbled over that)

using KSP 1.2.2

I'll report back if you need more
ty in advance!

``
[ERR 04:42:50.378] Module Variable ISP Engine threw during OnUpdate: System.NullReferenceException: Object reference not set to an instance of an object
  at NearFuturePropulsion.VariableISPEngine.OnUpdate () [0x00000] in <filename unknown>:0 
  at Part.ModulesOnUpdate () [0x00000] in <filename unknown>:0 
``

**Comment by ChrisAdderley** [comment]
Can't reproduce this.

**Comment by LouisCyfer** [comment]
lemme try in a stock + NF only save test, will report back after

**Comment by ChrisAdderley** [comment]
Make sure to use latest release (from this morning) please.

**Comment by LouisCyfer** [comment]
NFP has 0.6.1 as latest release from 20 Feb 2016

**Comment by ChrisAdderley** [comment]
You probably shouldn't use the git releases. They are in no way up to date.

**Comment by LouisCyfer** [comment]
I just found out, ty for the reply .. i assume the latest will fix my issues!

**Comment by ChrisAdderley** [comment]
Yup... let me know if it doesn't.

**Comment by LouisCyfer** [comment]
v0.8.3 works flawless, the origin issue report counts for the latest release on github which is version 0.6.1

**Comment by ChrisAdderley** [comment]
K cool, I am deleting that release to avoid confusion.
