### ISSUE TITLE
PIT engines use wrong/old thrust values.

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFuturePropulsion#5]
In the main ModuleEnginesFX module, the value for maxThrust is correctly set to the latest values. However, in the VariablePowerEngine module, the value for ConstantThrust still has older numbers that must be changed to match maxThrust.

Affects all three PIT thrusters.

**Comment by ChrisAdderley** [comment]
Well at least that's an easy enough fix!
