### ISSUE TITLE
KO-1 Pulsed Plasma RCS Thruster edits

### ISSUE THREAD

**Issue by Stratickus** [ChrisAdderley/NearFuturePropulsion#52]
Config file lacks manufacturer
			manufacturer = Kerbal Electric Drive Yards 

This part is not included in the CTT patch
			@TechRequired = plasmaPropulsion

**Comment by ChrisAdderley** [comment]
It's actually intended to be entry level and thus doesn't need a CTT patch... but I will fix the manufacturer.
