### ISSUE TITLE
Typo in VariableIspEngine Editor Display

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFuturePropulsion#55]
http://imgur.com/a/TNl0f

Secondary mode reads "s" where it should read "kN".

As an aside, the "ArgonMode Mode" thing looks a bit silly. ;) Also, the EngineID field in the config file seems unused (nothing else references what's written into it).

**Comment by ChrisAdderley** [comment]
This is all resolved in the upcoming 0.8.6!

**Comment by ChrisAdderley** [comment]
Confirmed resolved

**Comment by lOmicronl** [comment]
While you're hotfixing things:

A naughty little extra period snuck in this time :P 

http://i.imgur.com/XwM99yv.png

**Comment by ChrisAdderley** [comment]
Resolved that in bb3faad, for next release
