### ISSUE TITLE
0.625m VASIMR doesn't produce thrust in xenon mode

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFuturePropulsion#59]
Thrust is fine in argon mode, however. Other two VASIMRs not affected.

EDIT: DR. Jet says: "Most possible cause - "ThrustTransform" instead of "thrustTransform" in config. Unity is case-sensitive in terms of object naming."

**Comment by ChrisAdderley** [comment]
Was resolved
