### ISSUE TITLE
Misleading "Power Level" label on VASIMR tweakable

### ISSUE THREAD

**Issue by rspeed** [ChrisAdderley/NearFuturePropulsion#61]
Parts that implement the `VariableISPEngine` module include a tweakable labeled "Power Level". That implies that it changes the engine's thrust, which it does, but the relationship is inverted – increasing the value for "Power Level" actually *decreases* thrust. Since the trade-off is between specific impulse and thrust, perhaps it would make more sense to have the label read "Efficiency".

**Comment by Suprcheese** [comment]
Agreed, "Power Level" is a tad confusing, considering the actual effects.

**Comment by ChrisAdderley** [comment]
But power != thrust... 🤕

**Comment by rspeed** [comment]
It is colloquially. And regardless, that slider doesn't alter the power requirements (unlike `VariablePowerEngine`).

**Comment by ChrisAdderley** [comment]
07b087952f4033e37399fb3fa7b0f5faa725664f, will be in first 1.3 build.
