### ISSUE TITLE
model electrode erosion, like you do with the PPT.

### ISSUE THREAD

**Issue by toric55** [ChrisAdderley/NearFuturePropulsion#63]
Gridded ion engines and MPDs suffer from electrode erosion over their lifetime, meaning that each engine can only be used for so long in-between servicing. You currently model a similar mechanic with the pulsed plasma thruster. i can only find limited data on [MPDs](https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19880020476.pdf), which indicates between 2x10^4 N/s with ammonia, over .2 hours, 5x20^4 with argon, over 50 hours, and 1x10^6N/s, unspecified, over 500 hours. (I am looking for the reference). Lithium propellant should increase these somewhat. 

The [NSTAR](https://en.wikipedia.org/wiki/NASA_Solar_Technology_Application_Readinessl) thruster can last over 1.8 years of continuous operation. Obviously, this should be shortened to achieve the same total impulse over the lifetime of a thruster (as the thrust increases, the lifetime decreases) because the thrusters in ksp are considerably more powerful than the ones in real life. 

Of course, if the lifetime of the thruster is still measured in years, There is not a huge amount of pint in modeling it, but even realistic MPDs at low powers have quite short lifetimes. Maybe it would be an idea to model this? From a gameplay perspective, it would give a choice between PITs and MPDs, depending on the lifetime of the mission, and between xenon and hall thrusters, also depending on the mission. 

I would personally recommend using materialkits, metal, or machinery to represent the wear, and add a servicing mechanic, to allow kerbals to replace the electrode to continue operating on manned missions, Similar to NFEs radioactive storage mechanics. i will update when I hear back from NASA on the lifetime of lithium propellants.

While I'm on the subject, maybe replace the solidfuel resource in PPTs with the CRP resource polymers, and allow similar re servicing by EVA kerbals.

**Comment by ChrisAdderley** [comment]
I do not model electrode erosion with the PPT.

You look like you are looking for something this mod isn't here. This mod mirrors and extends stock gameplay - if stock adds turbopump wear and tear, nozzle ablation, random failures, part lifetime, etc, then I will do this. However, at the moment this makes far more sense as an addon to a mod like DangIt that models equipment wear and failures.

**Comment by toric55** [comment]
i don't really mean random failures. simply a maximum time between servicing. so, an MPD, if in an unmanned mission, can only consume so much fuel/give so much impulse per engine. if you have kerbals along, than you can go on EVA and replace the electrodes, allowing you to use the MPDs more. However, I see where you are coming from. 
as for the PPT, I meant the mechanic you used to model the wear of the teflon that is used as the fuel, giving the engine its own fuel supply that cannot be replenished.

Thank you for considering my suggestion.

**Comment by ChrisAdderley** [comment]
Yeah but in my opinion part lifetime and part failures fall under the same umbrella. Better modeled using a system that is designed to treat such things rather than tacked on to my mod. 

I see what you mean I suppose with the PPT, but to me that is more just that in this part I would consider the fuel to be integral to the engine, like an SRB.

That does point out to me that you can probably do it yourself as a patch. Just patch the engines to use a built-in unrefuellable resource like Ablator as a third propellant and then give the engine a cache of said propellant. Voila, instant lifetime!

**Comment by toric55** [comment]
so ive started work on modding them in myself, and would like permission to release them as an addon mod to near future, along with other tweaks to NF mods that i play with. (and other mod tweaks) also, I must say i am somewhat confused by the ratio entry in moduleengineFX, as the KSP wiki says it is the amount consumed per second, but in your .cfgs, it seems to be the ratio relative to all the other propellants, even though there is no absolute value given... anyway, do you know where i could find documentation for that? (yes, ill ask in addon dev, just thought I'd mention it.)

**Comment by toric55** [comment]
would it be possible to use the radioactivestoragecontainer module to handle the eva-only nature of the electrode resource?

**Comment by ChrisAdderley** [comment]
KSP wiki is very wrong about almost everything. It's ratio relative to all propellants with the absolute value determined by the thrust and Isp values. First find the mass flow rate:

F (kN) = g0 * Isp (s) * flow rate (t/s)

Then the mixture ratio is the sum of all propellant densities * their ratios over their total ratio:

mixture ratio = (propellant1 density * propellant1 ratio + ...)/ sum(propellant ratios)

The flow rate for each propellant is then

propellant flow rate = mass flow rate / mixture ratio * propellant ratio/ sum(propellant ratios)

Work this backwards if you want to find the ratios given a desired flow rate

**Comment by ChrisAdderley** [comment]
Closing this one

**Comment by toric55** [comment]
thanks. my question still stands though, do i have your blessing to release this as a separate mod?

**Comment by ChrisAdderley** [comment]
Yep go ahead, best if you do it all via MM. Don't redistribute NFP itself and such.
