### ISSUE TITLE
Tank dry mass review

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFuturePropulsion#7]
Xenon, argon and liquid hydrogen tanks all have different fuel/mass ratios. This is not yet accounted for in engine balance, resulting in some engines being as much as 8% above the baseline.

Also, the fuel/mass ratio of liquid hydrogen tanks affects the HydrogenNTRs patch negatively (see #6).

Unfortunately, changing tank masses to fix the first issue makes the second worse - and vice versa. A fundamental review of the whole setup is required.

Care must be taken, because changes in liquid hydrogen tanks are likely to affect the CryoEngines mod as well, making the problem even more complicated...

**Comment by ChrisAdderley** [comment]
As always, I'm open to ideas...

**Comment by lOmicronl** [comment]
There's a giant amount of stuff to write on this topic, and I think discussion with multiple people will help. Do you want to keep it here? In the NFT thread? In your dev thread?

**Comment by lOmicronl** [comment]
Following the discussion from this post onwards: http://forum.kerbalspaceprogram.com/index.php?/topic/47223-wip-nerts-dev-thread-current-nfpropulsion-balance/&page=57#comment-2308448

- Hydrogen tanks and NTR patch migrated out of NF Propulsion
- Lithium fuel introduced instead, used exclusively by MPDTs, with unique dry mass and price points
- Xenon and Argon dry mass aligned; xenon engines buffed slightly to ompensate price difference
- VASIMRs now run on argon/xenon instead of argon/hydrogen
- MPDTs fully re-statted for use with lithium

All open points resolved.
