### ISSUE TITLE
VariableISPEngine uses old gravity constant

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFuturePropulsion#8]
In legacy KSP, the value for gravity was set at 9.82. When KSP updated to 1.0, this was changed under the hood to use the proper value of 9.807. This results in an invisible loss of about 1%-2% thrust for VASIMR engines unless the plugin is updated to match.

**Comment by ChrisAdderley** [comment]
Fixed as per the pull request
