### ISSUE TITLE
Model Standardization

### ISSUE THREAD

**Issue by Electrocutor** [ChrisAdderley/NearFuturePropulsion#85]
@PART[mpdt-0625]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Engines/mpdt-0625/mpdt-0625
	}
}
@PART[mpdt-125]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Engines/mpdt-125/mpdt-125
	}
}
@PART[mpdt-25]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Engines/mpdt-25/mpdt-25
	}
}
@PART[pit-0625]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Engines/pit-0625/pit-0625
	}
}
@PART[pit-125]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Engines/pit-125/pit-125
	}
}
@PART[pit-25]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Engines/pit-25/pit-25
	}
}
@PART[vasimr-0625]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Engines/vasimr-0625/vasimr-0625
	}
}
@PART[vasimr-125]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Engines/vasimr-125/vasimr-125
	}
}
@PART[vasimr-25]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Engines/vasimr-25/vasimr-25
	}
}
@PART[cryoseperator-25]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Resources/cryoseperator-25/cryoseperator-25
	}
}
@PART[gasspectrometer-01]:NEEDS[NearFuturePropulsion]:FIRST {
	-mesh = DELETE
	MODEL {
		model = NearFuturePropulsion/Parts/Resources/gasspectrometer-01/gasspectrometer-01
	}
}

**Comment by ChrisAdderley** [comment]
PR would be nice ;).
